# Generated by Django 2.0.6 on 2018-06-12 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_auto_20180611_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end',
            field=models.DateField(default=datetime.datetime(2016, 7, 12, 10, 59, 24, 551834)),
        ),
        migrations.AddField(
            model_name='semester',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 7, 12, 10, 59, 24, 551790)),
        ),
    ]
