# Generated by Django 2.0.6 on 2019-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_auto_20180611_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='semester',
            name='start',
            field=models.DateField(default=None),
        ),
    ]
